project_id = "gsvdchdcbrfnxlmqehbg"

[functions.create-razorpay-order]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.calculate-delivery]
verify_jwt = false

[functions.google-distance]
verify_jwt = false